#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// Custom ESP32-WROOM/WROVER pinout from user-provided header.

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// Full-duplex I2S: INMP441 microphone and MAX98357A speaker share BCLK/WS.
// ESP-IDF naming:
//   dout = ESP32 output  -> MAX98357A DIN
//   din  = ESP32 input   <- INMP441 SD
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_26  // INMP441 SCK & MAX98357A BCLK
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_25  // INMP441 WS  & MAX98357A LRC
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_32  // ESP32 -> MAX98357A DIN
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_33  // INMP441 SD -> ESP32

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_NC
#define AUDIO_CODEC_PA_PIN  GPIO_NUM_NC

#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_5
#define ASR_BUTTON_GPIO         GPIO_NUM_19
#define BUILTIN_LED_GPIO        GPIO_NUM_2

#define ML307_RX_PIN            GPIO_NUM_16
#define ML307_TX_PIN            GPIO_NUM_17

#define DISPLAY_SDA_PIN GPIO_NUM_21
#define DISPLAY_SCL_PIN GPIO_NUM_22
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define LAMP_GPIO GPIO_NUM_18

#endif // _BOARD_CONFIG_H_
